url: https://jdelemar.github.io
baseurl: /APFT

# Site settings
title: APFT
author: "James Delemar"
email: your-email@domain.com
description: "Army Fitness APFT Calculator. Calculates and fills out Army Physical Fitness Test score cards and Army body fat worksheets based on U.S. Army APFT and weight control program standards."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/ArmyFitnessAPFTCalculator
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/JDelemar/APFT

# Build settings
markdown: kramdown
permalink: pretty